author = Artur Tarassow
email = atecon@posteo.de
version = 0.4
date = 2022-01-14
description = Collection of useful date time related tools
tags = C88
min-version = 2020c
public = create_iso8601_series dates_to_iso8601 date_to_iso8601 numeric_to_extended_iso8601 gdate_to_iso8601 iso8601_to_dates
data-requirement = no-data-ok
help = calendar_utils_help.txt
sample-script = calendar_utils_sample.inp
